### ISSUE TITLE
Verify GitHub Actions run on PRs

### ISSUE THREAD

**Issue by JonathanCSmith** [FrancisCrickInstitute/AIoD-Model-Registry#3]
As title

**Comment by JonathanCSmith** [comment]
I want to confirm / ensure that having run these tests is a visual blocker for PR merging in the github PR interface. I have no reason to doubt that this will work automatically, but it needs confirmation :D

**Comment by JonathanCSmith** [comment]
I think our organisation github account may not allow this.... :'( I'm investigating.

**Comment by sea-shunned** [comment]
I presumed you meant if someone submitted a PR that doesn't pass, then the PR could not be merged? Didn't realise there was something in the settings for this...

Happy to test it by submitting a wrong PR if needed!

**Comment by JonathanCSmith** [comment]
Exactly that! I've contacted our account admin to see if it is a feature we have :D

**Comment by JonathanCSmith** [comment]
@nickynw thanks for this! I wonder why the information I found didn't point to this possibility at all!!!

**Comment by JonathanCSmith** [comment]
Closed by #6
